//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA44Team02A_SportsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facility()
        {
            this.IssueTrans = new HashSet<IssueTran>();
        }
    
        public string FacilityCode { get; set; }
        public string TimeID { get; set; }
        public string FacilityName { get; set; }
        public string Status { get; set; }
        public Nullable<int> TotalStock { get; set; }
        public Nullable<int> AvailableSlot { get; set; }
        public Nullable<float> RentalCost { get; set; }
    
        public virtual TimeSlot TimeSlot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueTran> IssueTrans { get; set; }
    }
}
