//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA44Team02A_SportsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueTran
    {
        public string TransactionID { get; set; }
        public string MemberID { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateBooked { get; set; }
        public Nullable<float> RentalCost { get; set; }
        public string RentalStatus { get; set; }
        public string FacilityCode { get; set; }
        public string TimeID { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual MemberInformation MemberInformation { get; set; }
    }
}
