//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA44Team02A_SportsProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInformation
    {
        public string StaffID { get; set; }
        public string StaffName { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string ContactTitle { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
    }
}
